### ISSUE TITLE
Get error on mounting _data directory

### ISSUE THREAD

**Issue by ramyajena** [marco-lancini/docker_burp#5]
Hi Marc,
I use your repository to run burp. successfully build the image but when I spin up the container it shows no content on /home/tester (default directory) because you mount  "_data" directory to the working directory.

**Comment by marco-lancini** [comment]
Hi @ramyajena, could you please post the full error log?

**Comment by ramyajena** [comment]
Hi @marco-lancini, Thanks for your reply. The image is built successfully but can't run the container. I am getting the following error
![Screenshot from 2020-03-11 13-48-28](https://user-images.githubusercontent.com/60004752/76396538-5bd72e00-639f-11ea-9019-c5965fe6925b.png)
 log. Please check.

**Comment by marco-lancini** [comment]
Hi, have you replaced the placeholder file named `burp_free.jar` with your copy of Burp?

**Comment by ramyajena** [comment]
No, Actually I never used burp before so should I download the burp. Because I don't know how to get copy of the burp. So please help me with this

**Comment by marco-lancini** [comment]
You can find all the relevant information on their website: https://portswigger.net/burp
Closing this as this is not related to this repository.

**Comment by ramyajena** [comment]
okay thanks for your support
